import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en";

// Complete translations for the entire app
export const translations = {
  fr: {
    // Navigation
    home: "Accueil",
    live: "Live",
    random: "Random",
    messages: "Messages",
    profile: "Profil",
    
    // Home page
    discover: "Découvrir",
    nearby: "À proximité",
    noProfilesFound: "Aucun profil trouvé",
    modifyFilters: "Modifiez vos critères de recherche pour voir plus de profils",
    reset: "Réinitialiser",
    modify: "Modifier",
    
    // Filters
    filters: "Filtres",
    age: "Âge",
    years: "ans",
    maxDistance: "Distance max",
    km: "km",
    lookingFor: "Je recherche",
    women: "Femmes",
    men: "Hommes",
    nonBinary: "Non-binaire",
    trans: "Trans",
    everyone: "Tout le monde",
    applyFilters: "Appliquer les filtres",
    
    // Profile
    myProfile: "Mon Profil",
    verifiedProfile: "Profil vérifié",
    unverifiedProfile: "Profil non vérifié",
    emailVerified: "Email vérifié",
    emailPending: "Email en attente",
    limitReached: "Limite atteinte",
    retryIn: "Réessayez dans",
    remainingSends: "envoi(s) restant(s)",
    verifyMyEmail: "Vérifier mon email",
    resendEmail: "Renvoyer l'email",
    sending: "Envoi...",
    photoGallery: "Galerie photos",
    addPhoto: "Ajouter une photo",
    aboutMe: "À propos de moi",
    addBio: "Ajouter une bio",
    add: "Ajouter",
    gender: "Genre",
    birthday: "Date de naissance",
    occupation: "Profession",
    education: "Études",
    originCity: "Ville d'origine",
    height: "Taille",
    interests: "Centres d'intérêt",
    female: "Femme",
    male: "Homme",
    lgbt: "LGBT+",
    editProfile: "Modifier le profil",
    photos: "Photos",
    inviteFriends: "Inviter des amis",
    support: "Support",
    logout: "Déconnexion",
    
    // Settings
    settings: "Paramètres",
    notifications: "Notifications",
    pushNotifications: "Notifications push",
    pushDescription: "Recevoir des alertes pour les matchs, messages et activités",
    appearance: "Apparence",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    systemMode: "Système",
    language: "Langue",
    french: "Français",
    english: "English",
    privacyAndSecurity: "Confidentialité et sécurité",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    dataCollection: "Collecte des données",
    accountManagement: "Gestion du compte",
    deleteAccount: "Supprimer mon compte",
    deleteAccountWarning: "Cette action est irréversible",
    dataRetention: "Conservation des données",
    dataRetentionInfo: "Vos données sont supprimées 90 jours après la suppression du compte",
    storeGuidelines: "Directives des stores",
    confirmDelete: "Confirmer la suppression",
    deleteConfirmMessage: "Êtes-vous sûr de vouloir supprimer définitivement votre compte ? Toutes vos données seront supprimées après 90 jours conformément à notre politique de conservation.",
    cancel: "Annuler",
    delete: "Supprimer",
    saved: "Paramètres sauvegardés",
    communityGuidelines: "Règles de la communauté",
    safetyTips: "Conseils de sécurité",
    contentModeration: "Modération du contenu",
    userSafety: "Sécurité des utilisateurs",
    childSafety: "Protection des mineurs",
    contentPolicy: "Politique de contenu",
    userProtection: "Protection des utilisateurs",
    dataPrivacy: "Confidentialité des données",
    consequences: "Sanctions",
    reportingAndBlocking: "Signalement & blocage",
    exportData: "Exporter mes données",
    exportDataDescription: "Télécharger toutes vos données personnelles (RGPD)",
    exporting: "Export en cours...",
    exportSuccess: "Vos données ont été exportées avec succès",
    exportError: "Erreur lors de l'export des données",
    close: "Fermer",
    download: "Télécharger",
    deleting: "Suppression...",
    
    // Advanced Privacy Settings
    advancedPrivacy: "Paramètres de confidentialité avancés",
    profileVisibility: "Visibilité du profil",
    profileVisibilityDescription: "Contrôlez qui peut voir votre profil",
    visibleToAll: "Visible par tous",
    visibleToMatches: "Visible par mes matchs uniquement",
    invisible: "Mode invisible",
    whoCanContact: "Qui peut me contacter",
    whoCanContactDescription: "Contrôlez qui peut vous envoyer des messages",
    anyoneCanContact: "Tout le monde",
    matchesOnly: "Mes matchs uniquement",
    verifiedOnly: "Profils vérifiés uniquement",
    geographicBlocking: "Blocage géographique",
    geographicBlockingDescription: "Masquer votre profil dans certaines régions",
    blockMyCountry: "Masquer dans mon pays",
    blockNearby: "Masquer aux utilisateurs proches (-10 km)",
    noBlocking: "Aucun blocage",
    privacySettingsSaved: "Paramètres de confidentialité sauvegardés",
    
    // Match Modal
    itsAMatch: "C'est un match !",
    youAndMatch: "Vous et {name} vous êtes mutuellement likés",
    sendMessage: "Envoyer un message",
    keepSwiping: "Continuer à swiper",
    
    // Profile Modal
    bio: "Bio",
    noInfo: "Non renseigné",
    sendMessageTo: "Envoyer un message à",
    likeProfile: "Liker",
    superLikeProfile: "ZFlamme 🔥",
    
    // Toasts
    success: "Succès",
    error: "Erreur",
    profileUpdated: "Profil mis à jour",
    photoAdded: "Photo ajoutée",
    photoDeleted: "Photo supprimée",
    emailNotAvailable: "Email non disponible",
    verificationEmailSent: "Email de vérification envoyé ! ✉️",
    remainingEmailsToday: "Il vous reste {count} envoi(s) aujourd'hui.",
    lastSendOfDay: "C'était votre dernier envoi de la journée.",
    dailyLimitReached: "Limite journalière atteinte",
    errorSendingEmail: "Erreur lors de l'envoi de l'email",
    accountScheduledDeletion: "Votre compte a été programmé pour suppression. Vos données seront effacées sous 90 jours.",
    errorDeletingAccount: "Erreur lors de la suppression du compte",
    
    // Age Rating Page
    ageAdequacy: "Adéquation à l'âge",
    ageRatingInfo: "Informations sur la classification d'âge de Zembo",
    classification18: "Classification 18+",
    classification18Desc1: "Zembo est une application de rencontres exclusivement réservée aux personnes majeures (18 ans et plus).",
    classification18Desc2: "Cette restriction d'âge est imposée pour garantir un environnement sûr et approprié pour tous les utilisateurs.",
    mandatoryVerification: "Vérification obligatoire",
    verificationRequirements: "Pour utiliser Zembo, chaque utilisateur doit :",
    verificationReq1: "Déclarer sa date de naissance lors de l'inscription",
    verificationReq2: "Confirmer qu'il a 18 ans ou plus",
    verificationReq3: "Soumettre une vérification d'identité (pièce d'identité + selfie)",
    verificationExplanation: "La vérification d'identité permet de s'assurer que l'utilisateur correspond à la photo de sa pièce d'identité et qu'il respecte l'âge minimum requis.",
    prohibitedContent: "Contenus interdits",
    prohibitedContentIntro: "Les contenus suivants sont strictement interdits sur Zembo :",
    prohibitedContent1: "Contenu sexuellement explicite ou pornographique",
    prohibitedContent2: "Nudité ou images suggestives",
    prohibitedContent3: "Violence, harcèlement ou intimidation",
    prohibitedContent4: "Discours haineux ou discriminatoire",
    prohibitedContent5: "Contenu illégal ou frauduleux",
    prohibitedContent6: "Spam ou publicité non sollicitée",
    prohibitedContent7: "Usurpation d'identité",
    moderationAndReporting: "Modération et signalement",
    moderationIntro: "Zembo dispose d'un système de modération actif incluant :",
    moderation1: "Vérification manuelle des identités par notre équipe",
    moderation2: "Système de signalement accessible à tous les utilisateurs",
    moderation3: "Examen des signalements par des modérateurs",
    moderation4: "Sanctions (avertissement, suspension, bannissement)",
    moderationConclusion: "Tout utilisateur ne respectant pas nos règles peut être banni définitivement de la plateforme.",
    lastUpdated: "Dernière mise à jour : Janvier 2026",
    contactUs: "Pour toute question, contactez-nous à",
    back: "Retour",
    
    // Welcome screen
    findLove: "Trouvez l'amour",
    welcomeSubtitle: "Rejoignez des milliers de célibataires et trouvez votre âme sœur",
    createAccount: "Créer un compte",
    login: "Se connecter",
    acceptTermsPrompt: "Veuillez accepter les conditions pour continuer",
    iAcceptThe: "J'accepte les",
    andThe: "et la",
    termsOfUse: "Conditions d'utilisation",
    
    // ZGames
    welcomeTo: "Bienvenue sur",
    readyToPlay: "Es-tu prêt(e) à jouer ? 🎮",
    aiConsentRequired: "Tu dois accepter le consentement IA ci-dessus pour accéder à ce jeu.",
     zconnectDesc: "Appel vocal aléatoire avec un inconnu",
     speedDatingDesc: "Rencontres rapides en vidéo",
     oracleDesc: "Trouve ton match parfait par l'IA",
     compatibility: "Compatibilité",
     compatibilityDesc: "Test de compatibilité avec tous",
    
    // Live
    goLive: "Go Live",
    liveInProgress: "Lives en cours",
    joinBroadcast: "Rejoignez une diffusion",
    noLivesYet: "Aucun live en cours",
    beFirstToLive: "Soyez le premier à lancer un live !",
    startLive: "Lancer un Live",
    shareWithCommunity: "Partagez un moment avec votre communauté",
    liveThumbnail: "Vignette du live",
    profilePhoto: "Photo de profil",
    uploadImage: "Importer une image",
    changeImage: "Changer l'image",
    liveTitle: "Titre du live",
    liveTitlePlaceholder: "Ex: Soirée chill, venez discuter !",
    description: "Description",
    descriptionOptional: "Description (optionnel)",
    describeLive: "Décrivez votre live...",
    tags: "Tags",
    addTag: "Ajouter un tag",
    launching: "Lancement...",
    upload: "Upload...",
    viewers: "spectateurs",
    gifts: "Cadeaux",
    endLive: "Terminer le live",
    confirmEndLive: "Êtes-vous sûr de vouloir terminer ce live ?",
    
    // Messages
    conversations: "Conversations",
    newMatches: "Nouveaux matchs",
    noConversations: "Aucune conversation",
    startSwiping: "Commencez à swiper pour matcher !",
    typing: "écrit...",
    online: "En ligne",
    offline: "Hors ligne",
    sendAMessage: "Envoyer un message...",
    today: "Aujourd'hui",
    yesterday: "Hier",
    callHistory: "Historique des appels",
    calls: "Appels",
    missedCall: "Appel manqué",
    incomingCall: "Appel entrant",
    outgoingCall: "Appel sortant",
    
    // Likes page
    whoLikedMe: "Qui m'a liké",
    noLikesYet: "Aucun like pour le moment",
    noSuperLikesYet: "Aucune ZFlamme pour le moment",
    noRosesYet: "Aucune rose pour le moment",
    keepSwipingForLikes: "Continue à swiper pour attirer l'attention et recevoir tes premiers likes !",
    superLikesShowInterest: "Les ZFlammes 🔥 montrent un intérêt particulier. Continue à explorer !",
    rosesArePremium: "Les roses sont des cadeaux premium. Tu en recevras bientôt !",
    discoverProfiles: "Découvrir des profils",
    unlockWhoLikedYou: "Débloque qui t'a liké ! ✨",
    peopleLikedYou: "personne(s) t'ont liké. Passe à Gold pour voir leurs photos et matcher instantanément !",
    becomeGold: "Devenir Gold",
    
    // Profile card
    like: "LIKE",
    nope: "NOPE",
    zflamme: "ZFLAMME",
    
    // Chat
    blockUser: "Bloquer",
    reportUser: "Signaler",
    unblockUser: "Débloquer",
    userBlocked: "Utilisateur bloqué",
    userReported: "Utilisateur signalé",
    
    // Shop
    shop: "Boutique",
    coins: "Coins",
    subscriptions: "Abonnements",
    yourBalance: "Votre solde",
    buyCoins: "Acheter des coins",
    popular: "Populaire",
    bestValue: "Meilleur rapport",
    bonus: "bonus",
    perDay: "par jour",
    perWeek: "par semaine",
    perMonth: "par mois",
    unlimited: "Illimités",
    blurred: "Flouté",
    likesPerDay: "Likes par jour",
    superLikes: "Super Likes",
    seeWhoLikedYou: "Voir qui vous a liké",
    freeBoosts: "Boosts gratuits",
    rewind: "Retour en arrière",
    noAds: "Sans publicités",
    passport: "Passeport",
    advancedFilters: "Filtres avancés",
    prioritySupport: "Support prioritaire",
    currentPlan: "Plan actuel",
    subscribe: "S'abonner",
    currentBalance: "Solde actuel",
    priceIn: "Prix en",
    priorityMessages: "Messages prioritaires",
    platinumBadge: "Badge Platinum",
    readReceipts: "Accusés de lecture",
    incognitoMode: "Mode Incognito",
    priorityMatches: "Matchs prioritaires",
    
    // Calls
    missed: "Manqué",
    missedPlural: "manqués",
    noAnswer: "Non répondu",
    outgoing: "Sortant",
    incoming: "Entrant",
    
    // General actions
    continue: "Continuer",
    confirm: "Confirmer",
    save: "Enregistrer",
    edit: "Modifier",
    remove: "Supprimer",
    loading: "Chargement...",
    retry: "Réessayer",
    skip: "Passer",
    next: "Suivant",
    previous: "Précédent",
    done: "Terminé",
    yes: "Oui",
    no: "Non",
    
    // Z Connect game
    zConnect: "Z Connect",
    readyToMeet: "Es-tu prêt(e) à rencontrer quelqu'un ?",
    noProfileJustVoice: "Connecte-toi par la voix.",
    connectedByChance: "Tu seras mis(e) en relation avec quelqu'un qui partage tes intérêts.",
    start: "Commencer",
    limitReachedCalls: "Limite atteinte",
    callsRemaining: "appels restants",
    searchingForSomeone: "Recherche d'un profil compatible...",
    cancelSearch: "Annuler",
    otherPersonNotAvailable: "L'autre personne n'était pas disponible",
    noWorries: "Pas de soucis, on te trouve quelqu'un d'autre !",
    restartSearch: "Relancer la recherche",
    backToMenu: "Retour au menu",
    connectionRefused: "Connexion refusée",
    searchingAnotherProfile: "Recherche d'un autre profil compatible...",
    basedOnInterests: "Basé sur vos intérêts communs",
     
     // Additional UI texts
     noProfileAvailable: "Aucun profil disponible",
     beFirstInRegion: "Soyez le premier à vous inscrire dans votre région !",
     loadingProfile: "Chargement du profil...",
     connecting: "Connexion en cours...",
     connected: "Connecté",
     cameraDisabled: "Caméra désactivée",
     demoModeLiveKit: "Mode démo - LiveKit à intégrer",
     beautyFilters: "Filtres Beauté",
     enabled: "Activé",
     disabled: "Désactivé",
     presets: "Préréglages",
     advancedSettings: "Réglages avancés",
     none: "Aucun",
     natural: "Naturel",
     soft: "Doux",
     glamour: "Glamour",
     vivid: "Vif",
     smoothing: "Lissage",
     brightness: "Luminosité",
     contrast: "Contraste",
     saturation: "Saturation",
     warmth: "Chaleur",
     sharpness: "Netteté",
     
     // Admin translations
     administration: "Administration",
     reports: "Signalements",
     identities: "Identités",
     users: "Utilisateurs",
     bans: "Bans",
     communication: "Messages",
     games: "Jeux",
     emails: "Emails",
     maintenance: "Maintenance",
     settingsAdmin: "Paramètres",
     
     // Admin Stats
     totalUsers: "Utilisateurs",
     totalCalls: "Appels totaux",
     matchesCreated: "Matchs créés",
     activeCalls: "Appels actifs",
     pendingReports: "Signalements en attente",
     bannedUsers: "Utilisateurs bannis",
     
     // Admin Identity
     identityVerifications: "Vérifications d'identité",
     pendingRequests: "demande(s) en attente",
     noPendingRequests: "Aucune demande en attente",
     refresh: "Actualiser",
     pending: "En attente",
     approved: "Approuvés",
     rejected: "Refusés",
     all: "Tous",
     noVerificationsToDisplay: "Aucune vérification à afficher",
     submittedOn: "Soumis le",
     unknownUser: "Utilisateur inconnu",
     examine: "Examiner",
     rejectionReasonLabel: "Raison du refus",
     identityVerification: "Vérification d'identité",
     idDocument: "Pièce d'identité",
     selfie: "Selfie",
     rejectionReasonOptional: "Raison du refus (optionnel)",
     rejectionPlaceholder: "Ex: Photo floue, document illisible, visage non visible...",
     reject: "Refuser",
     approve: "Approuver",
     identityApproved: "Identité approuvée avec succès",
     requestRejected: "Demande refusée",
     errorLoadingVerifications: "Erreur lors du chargement des vérifications",
     errorUpdating: "Erreur lors de la mise à jour",
     
     // Admin Communication
     send: "Envoyer",
     predefinedMessages: "Messages prédéfinis",
     sendNotification: "Envoyer une notification",
     individual: "Individuel",
     allUsers: "Tous les utilisateurs",
     recipient: "Destinataire",
     selectUser: "Sélectionner un utilisateur",
     noName: "Sans nom",
     notificationType: "Type de notification",
     information: "Information",
     warning: "Avertissement",
     promotion: "Promotion",
     title: "Titre",
     notificationTitle: "Titre de la notification",
     message: "Message",
     messageContent: "Contenu du message...",
     push: "Push",
     email: "Email",
     fillAllFields: "Veuillez remplir tous les champs",
     selectRecipient: "Veuillez sélectionner un destinataire",
     selectChannel: "Veuillez sélectionner au moins un canal d'envoi",
     emailSentTo: "Email envoyé à",
     emailSentSuccess: "Email envoyé avec succès",
     pushRegistered: "Push enregistré",
     notificationPushRegistered: "Notification push enregistrée",
     errorSending: "Erreur lors de l'envoi",
     messageModified: "Message modifié",
     messageCreated: "Message créé",
     messageDeleted: "Message supprimé",
     errorSaving: "Erreur lors de la sauvegarde",
     errorDeleting: "Erreur lors de la suppression",
     predefinedMessageLoaded: "Message prédéfini chargé",
     noPredefinedMessages: "Aucun message prédéfini",
     new: "Nouveau",
     useMessage: "Utiliser",
     category: "Catégorie",
     general: "Général",
     editMessage: "Modifier le message",
     newMessage: "Nouveau message",
     messageTitle: "Titre du message",
     
     // Admin Notifications History
     notificationsHistory: "Historique des Notifications",
     filterByType: "Filtrer par type",
     allTypes: "Tous les types",
     announcements: "Annonces",
     warnings: "Avertissements",
     system: "Système",
     promotions: "Promotions",
     verifications: "Vérifications",
     deleteAll: "Tout supprimer",
     confirmDeleteAll: "Confirmer la suppression",
     confirmDeleteAllNotifications: "Êtes-vous sûr de vouloir supprimer toutes les notifications ?",
     irreversibleAction: "Cette action est irréversible.",
     deleteAllNotifications: "Supprimer tout",
     noNotificationsFound: "Aucune notification trouvée",
     deleteThisNotification: "Supprimer cette notification ?",
     notificationDeleted: "Notification supprimée",
     allNotificationsDeleted: "Toutes les notifications ont été supprimées",
     sent: "Envoyé",
     waitingStatus: "En attente",
     recipientLabel: "Destinataire",
     senderLabel: "Expéditeur",
     admin: "Admin",
     
     // Admin Settings
     discoverySettings: "Paramètres de découverte",
     discoverySettingsDesc: "Contrôlez le filtrage des profils dans le feed de découverte. Désactivez pour faciliter les tests.",
     filterLikedProfiles: "Filtrer les profils likés",
     filterLikedProfilesDesc: "Les profils déjà likés ne réapparaîtront pas dans le feed",
     filterMatches: "Filtrer les matchs",
     filterMatchesDesc: "Les profils déjà matchés ne réapparaîtront pas dans le feed",
     filterLeftSwipes: "Filtrer les swipes gauche (passes)",
     filterLeftSwipesDesc: "Les profils swipés à gauche ne réapparaîtront pas",
     socialNetworks: "Réseaux sociaux",
     socialNetworksDesc: "Configurez les liens vers vos réseaux sociaux affichés dans les emails.",
     legalLinks: "Liens légaux",
     legalLinksDesc: "Configurez les liens vers vos pages légales affichés dans les emails.",
     generalSettings: "Paramètres généraux",
     generalSettingsDesc: "Configurez les paramètres généraux de l'application.",
     discovery: "Découverte",
     networks: "Réseaux",
     legal: "Légal",
     settingsSaved: "Paramètres enregistrés avec succès",
     errorSavingSettings: "Erreur lors de l'enregistrement",
     errorLoadingSettings: "Erreur lors du chargement des paramètres",
     
     // Admin Maintenance
     maintenanceTools: "Outils de maintenance Z Connect",
     maintenanceDesc: "Nettoyer les sessions bloquées et la file d'attente pour débloquer le système",
     queueWaiting: "Queue - En attente",
     queueMatched: "Queue - Matchés",
     sessionsDeciding: "Sessions - Deciding",
     staleDeciding: "Deciding obsolètes",
     refreshStats: "Actualiser les statistiques",
     lastRefresh: "Dernière actualisation",
     never: "jamais",
     closeStaleDeciding: "Clôturer sessions 'deciding' obsolètes",
     sessionsWaitingOver5min: "Sessions en attente de décision depuis plus de 5 minutes",
     clean: "Nettoyer",
     closeAllDeciding: "Clôturer TOUTES les sessions 'deciding'",
     forceCloseAllDeciding: "Force la clôture de toutes les sessions en phase de décision",
     closeAll: "Tout clôturer",
     cleanStaleQueue: "Nettoyer queue obsolète",
     removeEntriesNoHeartbeat: "Supprimer les entrées sans heartbeat depuis plus de 2 minutes",
     resetEntireQueue: "Réinitialiser toute la queue",
     resetQueueDesc: "Supprime toutes les entrées de la file d'attente (action irréversible)",
     decidingSessionsClosed: "session(s) 'deciding' clôturée(s)",
     staleQueueEntriesRemoved: "entrée(s) de queue obsolètes supprimée(s)",
     queueCleared: "Queue vidée",
     entriesRemoved: "entrée(s) supprimée(s)",
     errorCleaning: "Erreur lors du nettoyage",
     errorResetting: "Erreur lors de la réinitialisation",
     
     // Admin Truth or Dare / Games
     total: "Total",
     truths: "Vérités",
     dares: "Défis",
     active: "Actifs",
     search: "Rechercher...",
     type: "Type",
     content: "Contenu",
     difficulty: "Difficulté",
     easy: "Facile",
     medium: "Moyen",
     hard: "Difficile",
     extreme: "Extrême",
     truth: "Vérité",
     dare: "Défi",
     newChallenge: "Nouveau défi",
     editChallenge: "Modifier le défi",
     challengeUpdated: "Défi mis à jour",
     challengeCreated: "Défi créé",
     challengeDeleted: "Défi supprimé",
     challengeActivated: "Défi activé",
     challengeDeactivated: "Défi désactivé",
     contentRequired: "Le contenu est requis",
     noChallengeFound: "Aucun défi trouvé",
     inactive: "Inactifs",
     status: "Statut",
     actions: "Actions",
     confirmDeleteChallenge: "Confirmer la suppression du défi",
     confirmDeleteChallengeDesc: "Cette action est irréversible. Le défi sera définitivement supprimé.",
     errorLoadingChallenges: "Erreur lors du chargement des défis",
     errorModifying: "Erreur lors de la modification",
     
     // Common admin errors
     errorLoadingData: "Erreur lors du chargement des données",
  },
  en: {
    // Navigation
    home: "Home",
    live: "Live",
    random: "Random",
    messages: "Messages",
    profile: "Profile",
    
    // Home page
    discover: "Discover",
    nearby: "Nearby",
    noProfilesFound: "No profiles found",
    modifyFilters: "Modify your search criteria to see more profiles",
    reset: "Reset",
    modify: "Modify",
    
    // Filters
    filters: "Filters",
    age: "Age",
    years: "years",
    maxDistance: "Max distance",
    km: "km",
    lookingFor: "I'm looking for",
    women: "Women",
    men: "Men",
    nonBinary: "Non-binary",
    trans: "Trans",
    everyone: "Everyone",
    applyFilters: "Apply filters",
    
    // Profile
    myProfile: "My Profile",
    verifiedProfile: "Verified profile",
    unverifiedProfile: "Unverified profile",
    emailVerified: "Email verified",
    emailPending: "Email pending",
    limitReached: "Limit reached",
    retryIn: "Retry in",
    remainingSends: "send(s) remaining",
    verifyMyEmail: "Verify my email",
    resendEmail: "Resend email",
    sending: "Sending...",
    photoGallery: "Photo gallery",
    addPhoto: "Add a photo",
    aboutMe: "About me",
    addBio: "Add a bio",
    add: "Add",
    gender: "Gender",
    birthday: "Date of birth",
    occupation: "Occupation",
    education: "Education",
    originCity: "Origin city",
    height: "Height",
    interests: "Interests",
    female: "Female",
    male: "Male",
    lgbt: "LGBT+",
    editProfile: "Edit profile",
    photos: "Photos",
    inviteFriends: "Invite friends",
    support: "Support",
    logout: "Logout",
    
    // Settings
    settings: "Settings",
    notifications: "Notifications",
    pushNotifications: "Push notifications",
    pushDescription: "Receive alerts for matches, messages and activities",
    appearance: "Appearance",
    darkMode: "Dark mode",
    lightMode: "Light mode",
    systemMode: "System",
    language: "Language",
    french: "Français",
    english: "English",
    privacyAndSecurity: "Privacy & Security",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    dataCollection: "Data Collection",
    accountManagement: "Account Management",
    deleteAccount: "Delete my account",
    deleteAccountWarning: "This action is irreversible",
    dataRetention: "Data Retention",
    dataRetentionInfo: "Your data is deleted 90 days after account deletion",
    storeGuidelines: "Store Guidelines",
    confirmDelete: "Confirm deletion",
    deleteConfirmMessage: "Are you sure you want to permanently delete your account? All your data will be deleted after 90 days according to our retention policy.",
    cancel: "Cancel",
    delete: "Delete",
    saved: "Settings saved",
    communityGuidelines: "Community Guidelines",
    safetyTips: "Safety Tips",
    contentModeration: "Content Moderation",
    userSafety: "User Safety",
    childSafety: "Child Safety",
    contentPolicy: "Content Policy",
    userProtection: "User Protection",
    dataPrivacy: "Data Privacy",
    consequences: "Consequences",
    reportingAndBlocking: "Reporting & Blocking",
    exportData: "Export my data",
    exportDataDescription: "Download all your personal data (GDPR)",
    exporting: "Exporting...",
    exportSuccess: "Your data has been exported successfully",
    exportError: "Error exporting data",
    close: "Close",
    download: "Download",
    deleting: "Deleting...",
    
    // Advanced Privacy Settings
    advancedPrivacy: "Advanced Privacy Settings",
    profileVisibility: "Profile Visibility",
    profileVisibilityDescription: "Control who can see your profile",
    visibleToAll: "Visible to all",
    visibleToMatches: "Visible to my matches only",
    invisible: "Invisible mode",
    whoCanContact: "Who can contact me",
    whoCanContactDescription: "Control who can send you messages",
    anyoneCanContact: "Anyone",
    matchesOnly: "My matches only",
    verifiedOnly: "Verified profiles only",
    geographicBlocking: "Geographic Blocking",
    geographicBlockingDescription: "Hide your profile in certain regions",
    blockMyCountry: "Hide in my country",
    blockNearby: "Hide from nearby users (-10 km)",
    noBlocking: "No blocking",
    privacySettingsSaved: "Privacy settings saved",
    
    // Match Modal
    itsAMatch: "It's a match!",
    youAndMatch: "You and {name} liked each other",
    sendMessage: "Send a message",
    keepSwiping: "Keep swiping",
    
    // Profile Modal
    bio: "Bio",
    noInfo: "Not specified",
    sendMessageTo: "Send a message to",
    likeProfile: "Like",
    superLikeProfile: "ZFlamme 🔥",
    
    // Toasts
    success: "Success",
    error: "Error",
    profileUpdated: "Profile updated",
    photoAdded: "Photo added",
    photoDeleted: "Photo deleted",
    emailNotAvailable: "Email not available",
    verificationEmailSent: "Verification email sent! ✉️",
    remainingEmailsToday: "You have {count} send(s) remaining today.",
    lastSendOfDay: "This was your last send of the day.",
    dailyLimitReached: "Daily limit reached",
    errorSendingEmail: "Error sending email",
    accountScheduledDeletion: "Your account has been scheduled for deletion. Your data will be erased within 90 days.",
    errorDeletingAccount: "Error deleting account",
    
    // Age Rating Page
    ageAdequacy: "Age Rating",
    ageRatingInfo: "Age classification information for Zembo",
    classification18: "18+ Classification",
    classification18Desc1: "Zembo is a dating app exclusively for adults (18 years and older).",
    classification18Desc2: "This age restriction is enforced to ensure a safe and appropriate environment for all users.",
    mandatoryVerification: "Mandatory Verification",
    verificationRequirements: "To use Zembo, each user must:",
    verificationReq1: "Provide their date of birth during registration",
    verificationReq2: "Confirm they are 18 years or older",
    verificationReq3: "Submit identity verification (ID document + selfie)",
    verificationExplanation: "Identity verification ensures that the user matches their ID photo and meets the minimum age requirement.",
    prohibitedContent: "Prohibited Content",
    prohibitedContentIntro: "The following content is strictly prohibited on Zembo:",
    prohibitedContent1: "Sexually explicit or pornographic content",
    prohibitedContent2: "Nudity or suggestive images",
    prohibitedContent3: "Violence, harassment or intimidation",
    prohibitedContent4: "Hate speech or discrimination",
    prohibitedContent5: "Illegal or fraudulent content",
    prohibitedContent6: "Spam or unsolicited advertising",
    prohibitedContent7: "Identity theft",
    moderationAndReporting: "Moderation and Reporting",
    moderationIntro: "Zembo has an active moderation system including:",
    moderation1: "Manual identity verification by our team",
    moderation2: "Reporting system accessible to all users",
    moderation3: "Review of reports by moderators",
    moderation4: "Sanctions (warning, suspension, ban)",
    moderationConclusion: "Any user not complying with our rules may be permanently banned from the platform.",
    lastUpdated: "Last updated: January 2026",
    contactUs: "For any questions, contact us at",
    back: "Back",
    
    // Welcome screen
    findLove: "Find Love",
    welcomeSubtitle: "Join thousands of singles and find your soulmate",
    createAccount: "Create Account",
    login: "Sign In",
    acceptTermsPrompt: "Please accept the terms to continue",
    iAcceptThe: "I accept the",
    andThe: "and the",
    termsOfUse: "Terms of Use",
    
    // ZGames
    welcomeTo: "Welcome to",
    readyToPlay: "Are you ready to play? 🎮",
    aiConsentRequired: "You must accept the AI consent above to access this game.",
     zconnectDesc: "Random voice call with a stranger",
     speedDatingDesc: "Fast video dating",
     oracleDesc: "Find your perfect match by AI",
     compatibility: "Compatibility",
     compatibilityDesc: "Compatibility test with everyone",
    
    // Live
    goLive: "Go Live",
    liveInProgress: "Live streams",
    joinBroadcast: "Join a broadcast",
    noLivesYet: "No live streams yet",
    beFirstToLive: "Be the first to go live!",
    startLive: "Start a Live",
    shareWithCommunity: "Share a moment with your community",
    liveThumbnail: "Live thumbnail",
    profilePhoto: "Profile photo",
    uploadImage: "Upload an image",
    changeImage: "Change image",
    liveTitle: "Live title",
    liveTitlePlaceholder: "E.g.: Chill night, come chat!",
    description: "Description",
    descriptionOptional: "Description (optional)",
    describeLive: "Describe your live...",
    tags: "Tags",
    addTag: "Add a tag",
    launching: "Launching...",
    upload: "Upload...",
    viewers: "viewers",
    gifts: "Gifts",
    endLive: "End live",
    confirmEndLive: "Are you sure you want to end this live?",
    
    // Messages
    conversations: "Conversations",
    newMatches: "New matches",
    noConversations: "No conversations",
    startSwiping: "Start swiping to match!",
    typing: "typing...",
    online: "Online",
    offline: "Offline",
    sendAMessage: "Send a message...",
    today: "Today",
    yesterday: "Yesterday",
    callHistory: "Call history",
    calls: "Calls",
    missedCall: "Missed call",
    incomingCall: "Incoming call",
    outgoingCall: "Outgoing call",
    
    // Likes page
    whoLikedMe: "Who liked me",
    noLikesYet: "No likes yet",
    noSuperLikesYet: "No ZFlammes yet",
    noRosesYet: "No roses yet",
    keepSwipingForLikes: "Keep swiping to get noticed and receive your first likes!",
    superLikesShowInterest: "ZFlammes 🔥 show special interest. Keep exploring!",
    rosesArePremium: "Roses are premium gifts. You'll receive some soon!",
    discoverProfiles: "Discover profiles",
    unlockWhoLikedYou: "Unlock who liked you! ✨",
    peopleLikedYou: "people liked you. Go Gold to see their photos and match instantly!",
    becomeGold: "Become Gold",
    
    // Profile card
    like: "LIKE",
    nope: "NOPE",
    zflamme: "ZFLAMME",
    
    // Chat
    blockUser: "Block",
    reportUser: "Report",
    unblockUser: "Unblock",
    userBlocked: "User blocked",
    userReported: "User reported",
    
    // Shop
    shop: "Shop",
    coins: "Coins",
    subscriptions: "Subscriptions",
    yourBalance: "Your balance",
    buyCoins: "Buy coins",
    popular: "Popular",
    bestValue: "Best value",
    bonus: "bonus",
    perDay: "per day",
    perWeek: "per week",
    perMonth: "per month",
    unlimited: "Unlimited",
    blurred: "Blurred",
    likesPerDay: "Likes per day",
    superLikes: "Super Likes",
    seeWhoLikedYou: "See who liked you",
    freeBoosts: "Free boosts",
    rewind: "Rewind",
    noAds: "No ads",
    passport: "Passport",
    advancedFilters: "Advanced filters",
    prioritySupport: "Priority support",
    currentPlan: "Current plan",
    subscribe: "Subscribe",
    currentBalance: "Current balance",
    priceIn: "Price in",
    priorityMessages: "Priority messages",
    platinumBadge: "Platinum badge",
    readReceipts: "Read receipts",
    incognitoMode: "Incognito mode",
    priorityMatches: "Priority matches",
    
    // Calls
    missed: "Missed",
    missedPlural: "missed",
    noAnswer: "No answer",
    outgoing: "Outgoing",
    incoming: "Incoming",
    
    // General actions
    continue: "Continue",
    confirm: "Confirm",
    save: "Save",
    edit: "Edit",
    remove: "Remove",
    loading: "Loading...",
    retry: "Retry",
    skip: "Skip",
    next: "Next",
    previous: "Previous",
    done: "Done",
    yes: "Yes",
    no: "No",
    
    // Z Connect game
    zConnect: "Z Connect",
    readyToMeet: "Are you ready to meet someone?",
    noProfileJustVoice: "Connect by voice.",
    connectedByChance: "You'll be matched with someone who shares your interests.",
    start: "Start",
    limitReachedCalls: "Limit reached",
    callsRemaining: "calls remaining",
    searchingForSomeone: "Finding a compatible profile...",
    cancelSearch: "Cancel",
    otherPersonNotAvailable: "The other person wasn't available",
    noWorries: "No worries, we'll find someone else!",
    restartSearch: "Search again",
    backToMenu: "Back to menu",
    connectionRefused: "Connection refused",
    searchingAnotherProfile: "Finding another compatible profile...",
    basedOnInterests: "Based on your shared interests",
     
     // Additional UI texts
     noProfileAvailable: "No profiles available",
     beFirstInRegion: "Be the first to sign up in your region!",
     loadingProfile: "Loading profile...",
     connecting: "Connecting...",
     connected: "Connected",
     cameraDisabled: "Camera disabled",
     demoModeLiveKit: "Demo mode - LiveKit integration",
     beautyFilters: "Beauty Filters",
     enabled: "Enabled",
     disabled: "Disabled",
     presets: "Presets",
     advancedSettings: "Advanced settings",
     none: "None",
     natural: "Natural",
     soft: "Soft",
     glamour: "Glamour",
     vivid: "Vivid",
     smoothing: "Smoothing",
     brightness: "Brightness",
     contrast: "Contrast",
     saturation: "Saturation",
     warmth: "Warmth",
     sharpness: "Sharpness",
     
     // Admin translations
     administration: "Administration",
     reports: "Reports",
     identities: "Identities",
     users: "Users",
     bans: "Bans",
     communication: "Messages",
     games: "Games",
     emails: "Emails",
     maintenance: "Maintenance",
     settingsAdmin: "Settings",
     
     // Admin Stats
     totalUsers: "Users",
     totalCalls: "Total calls",
     matchesCreated: "Matches created",
     activeCalls: "Active calls",
     pendingReports: "Pending reports",
     bannedUsers: "Banned users",
     
     // Admin Identity
     identityVerifications: "Identity verifications",
     pendingRequests: "pending request(s)",
     noPendingRequests: "No pending requests",
     refresh: "Refresh",
     pending: "Pending",
     approved: "Approved",
     rejected: "Rejected",
     all: "All",
     noVerificationsToDisplay: "No verifications to display",
     submittedOn: "Submitted on",
     unknownUser: "Unknown user",
     examine: "Examine",
     rejectionReasonLabel: "Rejection reason",
     identityVerification: "Identity verification",
     idDocument: "ID document",
     selfie: "Selfie",
     rejectionReasonOptional: "Rejection reason (optional)",
     rejectionPlaceholder: "E.g.: Blurry photo, unreadable document, face not visible...",
     reject: "Reject",
     approve: "Approve",
     identityApproved: "Identity approved successfully",
     requestRejected: "Request rejected",
     errorLoadingVerifications: "Error loading verifications",
     errorUpdating: "Error updating",
     
     // Admin Communication
     send: "Send",
     predefinedMessages: "Predefined messages",
     sendNotification: "Send a notification",
     individual: "Individual",
     allUsers: "All users",
     recipient: "Recipient",
     selectUser: "Select a user",
     noName: "No name",
     notificationType: "Notification type",
     information: "Information",
     warning: "Warning",
     promotion: "Promotion",
     title: "Title",
     notificationTitle: "Notification title",
     message: "Message",
     messageContent: "Message content...",
     push: "Push",
     email: "Email",
     fillAllFields: "Please fill in all fields",
     selectRecipient: "Please select a recipient",
     selectChannel: "Please select at least one sending channel",
     emailSentTo: "Email sent to",
     emailSentSuccess: "Email sent successfully",
     pushRegistered: "Push registered",
     notificationPushRegistered: "Push notification registered",
     errorSending: "Error sending",
     messageModified: "Message modified",
     messageCreated: "Message created",
     messageDeleted: "Message deleted",
     errorSaving: "Error saving",
     errorDeleting: "Error deleting",
     predefinedMessageLoaded: "Predefined message loaded",
     noPredefinedMessages: "No predefined messages",
     new: "New",
     useMessage: "Use",
     category: "Category",
     general: "General",
     editMessage: "Edit message",
     newMessage: "New message",
     messageTitle: "Message title",
     
     // Admin Notifications History
     notificationsHistory: "Notifications History",
     filterByType: "Filter by type",
     allTypes: "All types",
     announcements: "Announcements",
     warnings: "Warnings",
     system: "System",
     promotions: "Promotions",
     verifications: "Verifications",
     deleteAll: "Delete all",
     confirmDeleteAll: "Confirm deletion",
     confirmDeleteAllNotifications: "Are you sure you want to delete all notifications?",
     irreversibleAction: "This action is irreversible.",
     deleteAllNotifications: "Delete all",
     noNotificationsFound: "No notifications found",
     deleteThisNotification: "Delete this notification?",
     notificationDeleted: "Notification deleted",
     allNotificationsDeleted: "All notifications have been deleted",
     sent: "Sent",
     waitingStatus: "Pending",
     recipientLabel: "Recipient",
     senderLabel: "Sender",
     admin: "Admin",
     
     // Admin Settings
     discoverySettings: "Discovery settings",
     discoverySettingsDesc: "Control profile filtering in the discovery feed. Disable for easier testing.",
     filterLikedProfiles: "Filter liked profiles",
     filterLikedProfilesDesc: "Liked profiles won't reappear in the feed",
     filterMatches: "Filter matches",
     filterMatchesDesc: "Matched profiles won't reappear in the feed",
     filterLeftSwipes: "Filter left swipes (passes)",
     filterLeftSwipesDesc: "Left-swiped profiles won't reappear",
     socialNetworks: "Social networks",
     socialNetworksDesc: "Configure links to your social networks displayed in emails.",
     legalLinks: "Legal links",
     legalLinksDesc: "Configure links to your legal pages displayed in emails.",
     generalSettings: "General settings",
     generalSettingsDesc: "Configure general application settings.",
     discovery: "Discovery",
     networks: "Networks",
     legal: "Legal",
     settingsSaved: "Settings saved successfully",
     errorSavingSettings: "Error saving settings",
     errorLoadingSettings: "Error loading settings",
     
     // Admin Maintenance
     maintenanceTools: "Z Connect maintenance tools",
     maintenanceDesc: "Clean blocked sessions and queue to unblock the system",
     queueWaiting: "Queue - Waiting",
     queueMatched: "Queue - Matched",
     sessionsDeciding: "Sessions - Deciding",
     staleDeciding: "Stale deciding",
     refreshStats: "Refresh statistics",
     lastRefresh: "Last refresh",
     never: "never",
     closeStaleDeciding: "Close stale 'deciding' sessions",
     sessionsWaitingOver5min: "Sessions waiting for decision for more than 5 minutes",
     clean: "Clean",
     closeAllDeciding: "Close ALL 'deciding' sessions",
     forceCloseAllDeciding: "Force close all sessions in decision phase",
     closeAll: "Close all",
     cleanStaleQueue: "Clean stale queue",
     removeEntriesNoHeartbeat: "Remove entries without heartbeat for more than 2 minutes",
     resetEntireQueue: "Reset entire queue",
     resetQueueDesc: "Removes all queue entries (irreversible action)",
     decidingSessionsClosed: "'deciding' session(s) closed",
     staleQueueEntriesRemoved: "stale queue entry(ies) removed",
     queueCleared: "Queue cleared",
     entriesRemoved: "entry(ies) removed",
     errorCleaning: "Error cleaning",
     errorResetting: "Error resetting",
     
     // Admin Truth or Dare / Games
     total: "Total",
     truths: "Truths",
     dares: "Dares",
     active: "Active",
     search: "Search...",
     type: "Type",
     content: "Content",
     difficulty: "Difficulty",
     easy: "Easy",
     medium: "Medium",
     hard: "Hard",
     extreme: "Extreme",
     truth: "Truth",
     dare: "Dare",
     newChallenge: "New challenge",
     editChallenge: "Edit challenge",
     challengeUpdated: "Challenge updated",
     challengeCreated: "Challenge created",
     challengeDeleted: "Challenge deleted",
     challengeActivated: "Challenge activated",
     challengeDeactivated: "Challenge deactivated",
     contentRequired: "Content is required",
     noChallengeFound: "No challenge found",
     inactive: "Inactive",
     status: "Status",
     actions: "Actions",
     confirmDeleteChallenge: "Confirm challenge deletion",
     confirmDeleteChallengeDesc: "This action is irreversible. The challenge will be permanently deleted.",
     errorLoadingChallenges: "Error loading challenges",
     errorModifying: "Error modifying",
     
     // Common admin errors
     errorLoadingData: "Error loading data",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.fr;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("fr");

  useEffect(() => {
    const savedLang = localStorage.getItem("zembo-language") as Language;
    if (savedLang && (savedLang === "fr" || savedLang === "en")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("zembo-language", lang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export default LanguageContext;
