import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en";

// Complete translations for the entire app
export const translations = {
  fr: {
    // Navigation
    home: "Accueil",
    live: "Live",
    random: "Random",
    messages: "Messages",
    profile: "Profil",
    
    // Home page
    discover: "Découvrir",
    nearby: "À proximité",
    noProfilesFound: "Aucun profil trouvé",
    modifyFilters: "Modifiez vos critères de recherche pour voir plus de profils",
    reset: "Réinitialiser",
    modify: "Modifier",
    
    // Filters
    filters: "Filtres",
    age: "Âge",
    years: "ans",
    maxDistance: "Distance max",
    km: "km",
    lookingFor: "Je recherche",
    women: "Femmes",
    men: "Hommes",
    nonBinary: "Non-binaire",
    trans: "Trans",
    everyone: "Tout le monde",
    applyFilters: "Appliquer les filtres",
    
    // Profile
    myProfile: "Mon Profil",
    verifiedProfile: "Profil vérifié",
    unverifiedProfile: "Profil non vérifié",
    emailVerified: "Email vérifié",
    emailPending: "Email en attente",
    limitReached: "Limite atteinte",
    retryIn: "Réessayez dans",
    remainingSends: "envoi(s) restant(s)",
    verifyMyEmail: "Vérifier mon email",
    resendEmail: "Renvoyer l'email",
    sending: "Envoi...",
    photoGallery: "Galerie photos",
    addPhoto: "Ajouter une photo",
    aboutMe: "À propos de moi",
    addBio: "Ajouter une bio",
    add: "Ajouter",
    gender: "Genre",
    birthday: "Date de naissance",
    occupation: "Profession",
    education: "Études",
    originCity: "Ville d'origine",
    height: "Taille",
    interests: "Centres d'intérêt",
    female: "Femme",
    male: "Homme",
    lgbt: "LGBT+",
    editProfile: "Modifier le profil",
    photos: "Photos",
    inviteFriends: "Inviter des amis",
    support: "Support",
    logout: "Déconnexion",
    
    // Settings
    settings: "Paramètres",
    notifications: "Notifications",
    pushNotifications: "Notifications push",
    pushDescription: "Recevoir des alertes pour les matchs, messages et activités",
    appearance: "Apparence",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    systemMode: "Système",
    language: "Langue",
    french: "Français",
    english: "English",
    privacyAndSecurity: "Confidentialité et sécurité",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    dataCollection: "Collecte des données",
    accountManagement: "Gestion du compte",
    deleteAccount: "Supprimer mon compte",
    deleteAccountWarning: "Cette action est irréversible",
    dataRetention: "Conservation des données",
    dataRetentionInfo: "Vos données sont supprimées 90 jours après la suppression du compte",
    storeGuidelines: "Directives des stores",
    confirmDelete: "Confirmer la suppression",
    deleteConfirmMessage: "Êtes-vous sûr de vouloir supprimer définitivement votre compte ? Toutes vos données seront supprimées après 90 jours conformément à notre politique de conservation.",
    cancel: "Annuler",
    delete: "Supprimer",
    saved: "Paramètres sauvegardés",
    communityGuidelines: "Règles de la communauté",
    safetyTips: "Conseils de sécurité",
    contentModeration: "Modération du contenu",
    userSafety: "Sécurité des utilisateurs",
    childSafety: "Protection des mineurs",
    contentPolicy: "Politique de contenu",
    userProtection: "Protection des utilisateurs",
    dataPrivacy: "Confidentialité des données",
    consequences: "Sanctions",
    reportingAndBlocking: "Signalement & blocage",
    exportData: "Exporter mes données",
    exportDataDescription: "Télécharger toutes vos données personnelles (RGPD)",
    exporting: "Export en cours...",
    exportSuccess: "Vos données ont été exportées avec succès",
    exportError: "Erreur lors de l'export des données",
    close: "Fermer",
    download: "Télécharger",
    deleting: "Suppression...",
    
    // Advanced Privacy Settings
    advancedPrivacy: "Paramètres de confidentialité avancés",
    profileVisibility: "Visibilité du profil",
    profileVisibilityDescription: "Contrôlez qui peut voir votre profil",
    visibleToAll: "Visible par tous",
    visibleToMatches: "Visible par mes matchs uniquement",
    invisible: "Mode invisible",
    whoCanContact: "Qui peut me contacter",
    whoCanContactDescription: "Contrôlez qui peut vous envoyer des messages",
    anyoneCanContact: "Tout le monde",
    matchesOnly: "Mes matchs uniquement",
    verifiedOnly: "Profils vérifiés uniquement",
    geographicBlocking: "Blocage géographique",
    geographicBlockingDescription: "Masquer votre profil dans certaines régions",
    blockMyCountry: "Masquer dans mon pays",
    blockNearby: "Masquer aux utilisateurs proches (-10 km)",
    noBlocking: "Aucun blocage",
    privacySettingsSaved: "Paramètres de confidentialité sauvegardés",
    
    // Match Modal
    itsAMatch: "C'est un match !",
    youAndMatch: "Vous et {name} vous êtes mutuellement likés",
    sendMessage: "Envoyer un message",
    keepSwiping: "Continuer à swiper",
    
    // Profile Modal
    bio: "Bio",
    noInfo: "Non renseigné",
    sendMessageTo: "Envoyer un message à",
    likeProfile: "Liker",
    superLikeProfile: "ZFlamme 🔥",
    
    // Toasts
    success: "Succès",
    error: "Erreur",
    profileUpdated: "Profil mis à jour",
    photoAdded: "Photo ajoutée",
    photoDeleted: "Photo supprimée",
    emailNotAvailable: "Email non disponible",
    verificationEmailSent: "Email de vérification envoyé ! ✉️",
    remainingEmailsToday: "Il vous reste {count} envoi(s) aujourd'hui.",
    lastSendOfDay: "C'était votre dernier envoi de la journée.",
    dailyLimitReached: "Limite journalière atteinte",
    errorSendingEmail: "Erreur lors de l'envoi de l'email",
    accountScheduledDeletion: "Votre compte a été programmé pour suppression. Vos données seront effacées sous 90 jours.",
    errorDeletingAccount: "Erreur lors de la suppression du compte",
    
    // Age Rating Page
    ageAdequacy: "Adéquation à l'âge",
    ageRatingInfo: "Informations sur la classification d'âge de Zembo",
    classification18: "Classification 18+",
    classification18Desc1: "Zembo est une application de rencontres exclusivement réservée aux personnes majeures (18 ans et plus).",
    classification18Desc2: "Cette restriction d'âge est imposée pour garantir un environnement sûr et approprié pour tous les utilisateurs.",
    mandatoryVerification: "Vérification obligatoire",
    verificationRequirements: "Pour utiliser Zembo, chaque utilisateur doit :",
    verificationReq1: "Déclarer sa date de naissance lors de l'inscription",
    verificationReq2: "Confirmer qu'il a 18 ans ou plus",
    verificationReq3: "Soumettre une vérification d'identité (pièce d'identité + selfie)",
    verificationExplanation: "La vérification d'identité permet de s'assurer que l'utilisateur correspond à la photo de sa pièce d'identité et qu'il respecte l'âge minimum requis.",
    prohibitedContent: "Contenus interdits",
    prohibitedContentIntro: "Les contenus suivants sont strictement interdits sur Zembo :",
    prohibitedContent1: "Contenu sexuellement explicite ou pornographique",
    prohibitedContent2: "Nudité ou images suggestives",
    prohibitedContent3: "Violence, harcèlement ou intimidation",
    prohibitedContent4: "Discours haineux ou discriminatoire",
    prohibitedContent5: "Contenu illégal ou frauduleux",
    prohibitedContent6: "Spam ou publicité non sollicitée",
    prohibitedContent7: "Usurpation d'identité",
    moderationAndReporting: "Modération et signalement",
    moderationIntro: "Zembo dispose d'un système de modération actif incluant :",
    moderation1: "Vérification manuelle des identités par notre équipe",
    moderation2: "Système de signalement accessible à tous les utilisateurs",
    moderation3: "Examen des signalements par des modérateurs",
    moderation4: "Sanctions (avertissement, suspension, bannissement)",
    moderationConclusion: "Tout utilisateur ne respectant pas nos règles peut être banni définitivement de la plateforme.",
    lastUpdated: "Dernière mise à jour : Janvier 2026",
    contactUs: "Pour toute question, contactez-nous à",
    back: "Retour",
    
    // Welcome screen
    findLove: "Trouvez l'amour",
    welcomeSubtitle: "Rejoignez des milliers de célibataires et trouvez votre âme sœur",
    createAccount: "Créer un compte",
    login: "Se connecter",
    acceptTermsPrompt: "Veuillez accepter les conditions pour continuer",
    iAcceptThe: "J'accepte les",
    andThe: "et la",
    termsOfUse: "Conditions d'utilisation",
    
    // ZGames
    welcomeTo: "Bienvenue sur",
    readyToPlay: "Es-tu prêt(e) à jouer ? 🎮",
    aiConsentRequired: "Tu dois accepter le consentement IA ci-dessus pour accéder à ce jeu.",
    
    // Live
    goLive: "Go Live",
    liveInProgress: "Lives en cours",
    joinBroadcast: "Rejoignez une diffusion",
    noLivesYet: "Aucun live en cours",
    beFirstToLive: "Soyez le premier à lancer un live !",
    startLive: "Lancer un Live",
    shareWithCommunity: "Partagez un moment avec votre communauté",
    liveThumbnail: "Vignette du live",
    profilePhoto: "Photo de profil",
    uploadImage: "Importer une image",
    changeImage: "Changer l'image",
    liveTitle: "Titre du live",
    liveTitlePlaceholder: "Ex: Soirée chill, venez discuter !",
    description: "Description",
    descriptionOptional: "Description (optionnel)",
    describeLive: "Décrivez votre live...",
    tags: "Tags",
    addTag: "Ajouter un tag",
    launching: "Lancement...",
    upload: "Upload...",
    viewers: "spectateurs",
    gifts: "Cadeaux",
    endLive: "Terminer le live",
    confirmEndLive: "Êtes-vous sûr de vouloir terminer ce live ?",
    
    // Messages
    conversations: "Conversations",
    newMatches: "Nouveaux matchs",
    noConversations: "Aucune conversation",
    startSwiping: "Commencez à swiper pour matcher !",
    typing: "écrit...",
    online: "En ligne",
    offline: "Hors ligne",
    sendAMessage: "Envoyer un message...",
    today: "Aujourd'hui",
    yesterday: "Hier",
    callHistory: "Historique des appels",
    calls: "Appels",
    missedCall: "Appel manqué",
    incomingCall: "Appel entrant",
    outgoingCall: "Appel sortant",
    
    // Likes page
    whoLikedMe: "Qui m'a liké",
    noLikesYet: "Aucun like pour le moment",
    noSuperLikesYet: "Aucune ZFlamme pour le moment",
    noRosesYet: "Aucune rose pour le moment",
    keepSwipingForLikes: "Continue à swiper pour attirer l'attention et recevoir tes premiers likes !",
    superLikesShowInterest: "Les ZFlammes 🔥 montrent un intérêt particulier. Continue à explorer !",
    rosesArePremium: "Les roses sont des cadeaux premium. Tu en recevras bientôt !",
    discoverProfiles: "Découvrir des profils",
    unlockWhoLikedYou: "Débloque qui t'a liké ! ✨",
    peopleLikedYou: "personne(s) t'ont liké. Passe à Gold pour voir leurs photos et matcher instantanément !",
    becomeGold: "Devenir Gold",
    
    // Profile card
    like: "LIKE",
    nope: "NOPE",
    zflamme: "ZFLAMME",
    
    // Chat
    blockUser: "Bloquer",
    reportUser: "Signaler",
    unblockUser: "Débloquer",
    userBlocked: "Utilisateur bloqué",
    userReported: "Utilisateur signalé",
    
    // Shop
    shop: "Boutique",
    coins: "Coins",
    subscriptions: "Abonnements",
    yourBalance: "Votre solde",
    buyCoins: "Acheter des coins",
    popular: "Populaire",
    bestValue: "Meilleur rapport",
    bonus: "bonus",
    perDay: "par jour",
    perWeek: "par semaine",
    perMonth: "par mois",
    unlimited: "Illimités",
    blurred: "Flouté",
    likesPerDay: "Likes par jour",
    superLikes: "Super Likes",
    seeWhoLikedYou: "Voir qui vous a liké",
    freeBoosts: "Boosts gratuits",
    rewind: "Retour en arrière",
    noAds: "Sans publicités",
    passport: "Passeport",
    advancedFilters: "Filtres avancés",
    prioritySupport: "Support prioritaire",
    currentPlan: "Plan actuel",
    subscribe: "S'abonner",
    
    // General actions
    continue: "Continuer",
    confirm: "Confirmer",
    save: "Enregistrer",
    edit: "Modifier",
    remove: "Supprimer",
    loading: "Chargement...",
    retry: "Réessayer",
    skip: "Passer",
    next: "Suivant",
    previous: "Précédent",
    done: "Terminé",
    yes: "Oui",
    no: "Non",
    
    // Z Connect game
    zConnect: "Z Connect",
    readyToMeet: "Es-tu prêt(e) à rencontrer quelqu'un ?",
    noProfileJustVoice: "Aucun profil, juste une voix.",
    connectedByChance: "Tu vas être connecté(e) avec une personne choisie par le hasard.",
    start: "Commencer",
    limitReachedCalls: "Limite atteinte",
    callsRemaining: "appels restants",
    searchingForSomeone: "Recherche en cours...",
    cancelSearch: "Annuler",
    otherPersonNotAvailable: "L'autre personne n'était pas disponible",
    noWorries: "Pas de soucis, on te trouve quelqu'un d'autre !",
    restartSearch: "Relancer la recherche",
    backToMenu: "Retour au menu",
    connectionRefused: "Connexion refusée",
    searchingAnotherProfile: "Recherche d'un autre profil...",
  },
  en: {
    // Navigation
    home: "Home",
    live: "Live",
    random: "Random",
    messages: "Messages",
    profile: "Profile",
    
    // Home page
    discover: "Discover",
    nearby: "Nearby",
    noProfilesFound: "No profiles found",
    modifyFilters: "Modify your search criteria to see more profiles",
    reset: "Reset",
    modify: "Modify",
    
    // Filters
    filters: "Filters",
    age: "Age",
    years: "years",
    maxDistance: "Max distance",
    km: "km",
    lookingFor: "I'm looking for",
    women: "Women",
    men: "Men",
    nonBinary: "Non-binary",
    trans: "Trans",
    everyone: "Everyone",
    applyFilters: "Apply filters",
    
    // Profile
    myProfile: "My Profile",
    verifiedProfile: "Verified profile",
    unverifiedProfile: "Unverified profile",
    emailVerified: "Email verified",
    emailPending: "Email pending",
    limitReached: "Limit reached",
    retryIn: "Retry in",
    remainingSends: "send(s) remaining",
    verifyMyEmail: "Verify my email",
    resendEmail: "Resend email",
    sending: "Sending...",
    photoGallery: "Photo gallery",
    addPhoto: "Add a photo",
    aboutMe: "About me",
    addBio: "Add a bio",
    add: "Add",
    gender: "Gender",
    birthday: "Date of birth",
    occupation: "Occupation",
    education: "Education",
    originCity: "Origin city",
    height: "Height",
    interests: "Interests",
    female: "Female",
    male: "Male",
    lgbt: "LGBT+",
    editProfile: "Edit profile",
    photos: "Photos",
    inviteFriends: "Invite friends",
    support: "Support",
    logout: "Logout",
    
    // Settings
    settings: "Settings",
    notifications: "Notifications",
    pushNotifications: "Push notifications",
    pushDescription: "Receive alerts for matches, messages and activities",
    appearance: "Appearance",
    darkMode: "Dark mode",
    lightMode: "Light mode",
    systemMode: "System",
    language: "Language",
    french: "Français",
    english: "English",
    privacyAndSecurity: "Privacy & Security",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    dataCollection: "Data Collection",
    accountManagement: "Account Management",
    deleteAccount: "Delete my account",
    deleteAccountWarning: "This action is irreversible",
    dataRetention: "Data Retention",
    dataRetentionInfo: "Your data is deleted 90 days after account deletion",
    storeGuidelines: "Store Guidelines",
    confirmDelete: "Confirm deletion",
    deleteConfirmMessage: "Are you sure you want to permanently delete your account? All your data will be deleted after 90 days according to our retention policy.",
    cancel: "Cancel",
    delete: "Delete",
    saved: "Settings saved",
    communityGuidelines: "Community Guidelines",
    safetyTips: "Safety Tips",
    contentModeration: "Content Moderation",
    userSafety: "User Safety",
    childSafety: "Child Safety",
    contentPolicy: "Content Policy",
    userProtection: "User Protection",
    dataPrivacy: "Data Privacy",
    consequences: "Consequences",
    reportingAndBlocking: "Reporting & Blocking",
    exportData: "Export my data",
    exportDataDescription: "Download all your personal data (GDPR)",
    exporting: "Exporting...",
    exportSuccess: "Your data has been exported successfully",
    exportError: "Error exporting data",
    close: "Close",
    download: "Download",
    deleting: "Deleting...",
    
    // Advanced Privacy Settings
    advancedPrivacy: "Advanced Privacy Settings",
    profileVisibility: "Profile Visibility",
    profileVisibilityDescription: "Control who can see your profile",
    visibleToAll: "Visible to all",
    visibleToMatches: "Visible to my matches only",
    invisible: "Invisible mode",
    whoCanContact: "Who can contact me",
    whoCanContactDescription: "Control who can send you messages",
    anyoneCanContact: "Anyone",
    matchesOnly: "My matches only",
    verifiedOnly: "Verified profiles only",
    geographicBlocking: "Geographic Blocking",
    geographicBlockingDescription: "Hide your profile in certain regions",
    blockMyCountry: "Hide in my country",
    blockNearby: "Hide from nearby users (-10 km)",
    noBlocking: "No blocking",
    privacySettingsSaved: "Privacy settings saved",
    
    // Match Modal
    itsAMatch: "It's a match!",
    youAndMatch: "You and {name} liked each other",
    sendMessage: "Send a message",
    keepSwiping: "Keep swiping",
    
    // Profile Modal
    bio: "Bio",
    noInfo: "Not specified",
    sendMessageTo: "Send a message to",
    likeProfile: "Like",
    superLikeProfile: "ZFlamme 🔥",
    
    // Toasts
    success: "Success",
    error: "Error",
    profileUpdated: "Profile updated",
    photoAdded: "Photo added",
    photoDeleted: "Photo deleted",
    emailNotAvailable: "Email not available",
    verificationEmailSent: "Verification email sent! ✉️",
    remainingEmailsToday: "You have {count} send(s) remaining today.",
    lastSendOfDay: "This was your last send of the day.",
    dailyLimitReached: "Daily limit reached",
    errorSendingEmail: "Error sending email",
    accountScheduledDeletion: "Your account has been scheduled for deletion. Your data will be erased within 90 days.",
    errorDeletingAccount: "Error deleting account",
    
    // Age Rating Page
    ageAdequacy: "Age Rating",
    ageRatingInfo: "Age classification information for Zembo",
    classification18: "18+ Classification",
    classification18Desc1: "Zembo is a dating app exclusively for adults (18 years and older).",
    classification18Desc2: "This age restriction is enforced to ensure a safe and appropriate environment for all users.",
    mandatoryVerification: "Mandatory Verification",
    verificationRequirements: "To use Zembo, each user must:",
    verificationReq1: "Provide their date of birth during registration",
    verificationReq2: "Confirm they are 18 years or older",
    verificationReq3: "Submit identity verification (ID document + selfie)",
    verificationExplanation: "Identity verification ensures that the user matches their ID photo and meets the minimum age requirement.",
    prohibitedContent: "Prohibited Content",
    prohibitedContentIntro: "The following content is strictly prohibited on Zembo:",
    prohibitedContent1: "Sexually explicit or pornographic content",
    prohibitedContent2: "Nudity or suggestive images",
    prohibitedContent3: "Violence, harassment or intimidation",
    prohibitedContent4: "Hate speech or discrimination",
    prohibitedContent5: "Illegal or fraudulent content",
    prohibitedContent6: "Spam or unsolicited advertising",
    prohibitedContent7: "Identity theft",
    moderationAndReporting: "Moderation and Reporting",
    moderationIntro: "Zembo has an active moderation system including:",
    moderation1: "Manual identity verification by our team",
    moderation2: "Reporting system accessible to all users",
    moderation3: "Review of reports by moderators",
    moderation4: "Sanctions (warning, suspension, ban)",
    moderationConclusion: "Any user not complying with our rules may be permanently banned from the platform.",
    lastUpdated: "Last updated: January 2026",
    contactUs: "For any questions, contact us at",
    back: "Back",
    
    // Welcome screen
    findLove: "Find Love",
    welcomeSubtitle: "Join thousands of singles and find your soulmate",
    createAccount: "Create Account",
    login: "Sign In",
    acceptTermsPrompt: "Please accept the terms to continue",
    iAcceptThe: "I accept the",
    andThe: "and the",
    termsOfUse: "Terms of Use",
    
    // ZGames
    welcomeTo: "Welcome to",
    readyToPlay: "Are you ready to play? 🎮",
    aiConsentRequired: "You must accept the AI consent above to access this game.",
    
    // Live
    goLive: "Go Live",
    liveInProgress: "Live streams",
    joinBroadcast: "Join a broadcast",
    noLivesYet: "No live streams yet",
    beFirstToLive: "Be the first to go live!",
    startLive: "Start a Live",
    shareWithCommunity: "Share a moment with your community",
    liveThumbnail: "Live thumbnail",
    profilePhoto: "Profile photo",
    uploadImage: "Upload an image",
    changeImage: "Change image",
    liveTitle: "Live title",
    liveTitlePlaceholder: "E.g.: Chill night, come chat!",
    description: "Description",
    descriptionOptional: "Description (optional)",
    describeLive: "Describe your live...",
    tags: "Tags",
    addTag: "Add a tag",
    launching: "Launching...",
    upload: "Upload...",
    viewers: "viewers",
    gifts: "Gifts",
    endLive: "End live",
    confirmEndLive: "Are you sure you want to end this live?",
    
    // Messages
    conversations: "Conversations",
    newMatches: "New matches",
    noConversations: "No conversations",
    startSwiping: "Start swiping to match!",
    typing: "typing...",
    online: "Online",
    offline: "Offline",
    sendAMessage: "Send a message...",
    today: "Today",
    yesterday: "Yesterday",
    callHistory: "Call history",
    calls: "Calls",
    missedCall: "Missed call",
    incomingCall: "Incoming call",
    outgoingCall: "Outgoing call",
    
    // Likes page
    whoLikedMe: "Who liked me",
    noLikesYet: "No likes yet",
    noSuperLikesYet: "No ZFlammes yet",
    noRosesYet: "No roses yet",
    keepSwipingForLikes: "Keep swiping to get noticed and receive your first likes!",
    superLikesShowInterest: "ZFlammes 🔥 show special interest. Keep exploring!",
    rosesArePremium: "Roses are premium gifts. You'll receive some soon!",
    discoverProfiles: "Discover profiles",
    unlockWhoLikedYou: "Unlock who liked you! ✨",
    peopleLikedYou: "people liked you. Go Gold to see their photos and match instantly!",
    becomeGold: "Become Gold",
    
    // Profile card
    like: "LIKE",
    nope: "NOPE",
    zflamme: "ZFLAMME",
    
    // Chat
    blockUser: "Block",
    reportUser: "Report",
    unblockUser: "Unblock",
    userBlocked: "User blocked",
    userReported: "User reported",
    
    // Shop
    shop: "Shop",
    coins: "Coins",
    subscriptions: "Subscriptions",
    yourBalance: "Your balance",
    buyCoins: "Buy coins",
    popular: "Popular",
    bestValue: "Best value",
    bonus: "bonus",
    perDay: "per day",
    perWeek: "per week",
    perMonth: "per month",
    unlimited: "Unlimited",
    blurred: "Blurred",
    likesPerDay: "Likes per day",
    superLikes: "Super Likes",
    seeWhoLikedYou: "See who liked you",
    freeBoosts: "Free boosts",
    rewind: "Rewind",
    noAds: "No ads",
    passport: "Passport",
    advancedFilters: "Advanced filters",
    prioritySupport: "Priority support",
    currentPlan: "Current plan",
    subscribe: "Subscribe",
    
    // General actions
    continue: "Continue",
    confirm: "Confirm",
    save: "Save",
    edit: "Edit",
    remove: "Remove",
    loading: "Loading...",
    retry: "Retry",
    skip: "Skip",
    next: "Next",
    previous: "Previous",
    done: "Done",
    yes: "Yes",
    no: "No",
    
    // Z Connect game
    zConnect: "Z Connect",
    readyToMeet: "Are you ready to meet someone?",
    noProfileJustVoice: "No profile, just a voice.",
    connectedByChance: "You'll be connected with someone chosen by chance.",
    start: "Start",
    limitReachedCalls: "Limit reached",
    callsRemaining: "calls remaining",
    searchingForSomeone: "Searching...",
    cancelSearch: "Cancel",
    otherPersonNotAvailable: "The other person wasn't available",
    noWorries: "No worries, we'll find someone else!",
    restartSearch: "Search again",
    backToMenu: "Back to menu",
    connectionRefused: "Connection refused",
    searchingAnotherProfile: "Searching for another profile...",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.fr;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("fr");

  useEffect(() => {
    const savedLang = localStorage.getItem("zembo-language") as Language;
    if (savedLang && (savedLang === "fr" || savedLang === "en")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("zembo-language", lang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export default LanguageContext;
