-- Ajout de 100 nouvelles questions de compatibilité Zembo
INSERT INTO public.compatibility_questions (question, category, options, display_order, is_active) VALUES
-- 💘 AMOUR & RELATION (16-30)
('Que recherches-tu principalement ?', 'amour', '["💘 Relation sérieuse", "🔥 Fun & détente", "👋 Amitié", "🎲 On verra"]', 16, true),
('Pour toi, l''amour c''est plutôt :', 'amour', '["🏗️ Une construction", "✨ Une évidence", "🚀 Une aventure", "💪 Un défi"]', 17, true),
('Quelle est la base d''un couple solide ?', 'amour', '["🤝 Confiance", "💬 Communication", "🙏 Respect", "🔥 Passion"]', 18, true),
('En couple, tu es plutôt :', 'amour', '["💝 Très attentionné(e)", "🦅 Indépendant(e)", "💞 Fusionnel(le)", "🛡️ Protecteur(trice)"]', 19, true),
('Tu crois au coup de foudre ?', 'amour', '["⚡ Oui", "❌ Non", "🤔 Parfois"]', 20, true),
('Quelle place prend l''amour dans ta vie ?', 'amour', '["👑 Priorité", "💖 Important", "📋 Secondaire", "🎯 Optionnel"]', 21, true),
('Tu préfères :', 'amour', '["⚓ Relation stable", "🔥 Relation intense", "🦋 Relation libre", "📈 Relation évolutive"]', 22, true),
('Ton langage de l''amour principal :', 'amour', '["💬 Paroles valorisantes", "⏰ Temps de qualité", "🎁 Cadeaux", "🤲 Services rendus"]', 23, true),
('Pour toi, tromper c''est :', 'amour', '["💋 Physique", "💔 Émotionnel", "⚠️ Les deux", "🤷 Ça dépend"]', 24, true),
('Tu es plutôt :', 'amour', '["🌹 Romantique", "🧠 Pragmatique", "🔥 Passionné(e)", "🤫 Réservé(e)"]', 25, true),
('Tu crois à l''âme sœur ?', 'amour', '["💫 Oui", "❌ Non", "🤔 J''hésite"]', 26, true),
('Ta plus grande peur en amour ?', 'amour', '["🗡️ Trahison", "👋 Abandon", "😴 Routine", "🔗 Perte de liberté"]', 27, true),
('En cas de conflit, tu préfères :', 'amour', '["🗣️ Discuter calmement", "🧘 Prendre du recul", "⚡ Régler vite", "🚶 Éviter"]', 28, true),
('Pour toi, un couple doit évoluer :', 'amour', '["👫 Ensemble", "🚶🚶 Chacun de son côté", "⏳ À son rythme"]', 29, true),
('L''amour idéal selon toi :', 'amour', '["☮️ Paisible", "🔥 Passionnel", "⚓ Stable", "🌍 Aventurier"]', 30, true),

-- 🧠 PERSONNALITÉ & CARACTÈRE (31-45)
('Tu te définis plutôt comme :', 'personnalité', '["🧘 Calme", "⚡ Dynamique", "🎉 Sociable", "🤫 Réservé(e)"]', 31, true),
('Ton défaut principal :', 'personnalité', '["⏰ Impatience", "💚 Jalousie", "👑 Fierté", "💧 Sensibilité"]', 32, true),
('Ta plus grande qualité :', 'personnalité', '["🛡️ Loyauté", "💝 Gentillesse", "🎯 Ambition", "💎 Honnêteté"]', 33, true),
('Tu es plutôt :', 'personnalité', '["👑 Leader", "🤝 Suiveur(se)", "🦅 Indépendant(e)", "🤲 Collaboratif(ve)"]', 34, true),
('Tu réagis comment au stress ?', 'personnalité', '["💪 Je gère", "😰 Je panique", "🐚 Je me referme", "🧘 Je relativise"]', 35, true),
('Ton niveau d''émotivité :', 'personnalité', '["🌊 Très élevé", "⚖️ Moyen", "🧊 Faible"]', 36, true),
('Ton tempérament :', 'personnalité', '["🔥 Feu", "💧 Eau", "💨 Air", "🌍 Terre"]', 37, true),
('Tu prends tes décisions :', 'personnalité', '["💖 Avec le cœur", "🧠 Avec la tête", "⚖️ Les deux"]', 38, true),
('Tu es plutôt :', 'personnalité', '["📋 Organisé(e)", "🎲 Spontané(e)", "🔄 Un mélange"]', 39, true),
('Ta zone de confort :', 'personnalité', '["🛡️ Sécurité", "🚀 Aventure", "🦋 Liberté", "⚓ Stabilité"]', 40, true),
('Tu préfères :', 'personnalité', '["🗣️ Parler", "👂 Écouter", "👀 Observer"]', 41, true),
('Ta plus grande motivation :', 'personnalité', '["🏆 Succès", "👨‍👩‍👧 Famille", "🦋 Liberté", "🌍 Impact"]', 42, true),
('Tu pardonnes facilement ?', 'personnalité', '["✅ Oui", "❌ Non", "🤔 Ça dépend"]', 43, true),
('Tu crois plus en :', 'personnalité', '["✨ Destin", "💪 Travail", "🎲 Hasard", "🙏 Foi"]', 44, true),
('Tu es plutôt :', 'personnalité', '["☀️ Optimiste", "⚖️ Réaliste", "🌧️ Pessimiste"]', 45, true),

-- 🌍 STYLE DE VIE (46-60)
('Ta soirée idéale :', 'lifestyle', '["🎬 Netflix", "🍽️ Sortie resto", "👯 Soirée entre amis", "✈️ Voyage improvisé"]', 46, true),
('Tu préfères vivre :', 'lifestyle', '["🏙️ En ville", "🌾 À la campagne", "🏖️ En bord de mer"]', 47, true),
('Ton rythme de vie :', 'lifestyle', '["🐢 Tranquille", "🏃 Actif", "🚀 Très intense"]', 48, true),
('Tu voyages plutôt pour :', 'lifestyle', '["🗺️ Découvrir", "🧘 Te détendre", "🎉 Faire la fête", "💼 Travailler"]', 49, true),
('Tu es plutôt :', 'lifestyle', '["🏠 Casanier(e)", "🌍 Aventurier(e)"]', 50, true),
('Ton rapport à l''argent :', 'lifestyle', '["💸 Je dépense", "💰 J''économise", "📈 J''investis", "⚖️ J''équilibre"]', 51, true),
('Le travail pour toi :', 'lifestyle', '["❤️ Passion", "📋 Obligation", "🚀 Tremplin", "🛡️ Sécurité"]', 52, true),
('Ton rythme sportif :', 'lifestyle', '["🏋️ Régulier", "🎯 Occasionnel", "🛋️ Jamais"]', 53, true),
('Tu préfères :', 'lifestyle', '["📅 Planifier", "🎲 Improviser"]', 54, true),
('Ton environnement idéal :', 'lifestyle', '["🧘 Calme", "🎉 Animé", "🌿 Nature", "✨ Luxe"]', 55, true),
('Tu es plutôt :', 'lifestyle', '["🌅 Matinal(e)", "🌙 Nocturne"]', 56, true),
('Ton style vestimentaire :', 'lifestyle', '["👔 Chic", "👕 Casual", "🧢 Street", "🎨 Mix"]', 57, true),
('Tu préfères :', 'lifestyle', '["✨ Simplicité", "🛋️ Confort", "👗 Élégance", "🎭 Originalité"]', 58, true),
('Ton rapport au digital :', 'lifestyle', '["📱 Accro", "⚖️ Modéré", "📵 Minimal"]', 59, true),
('Tu es plus :', 'lifestyle', '["🏠 Maison", "🌃 Sorties"]', 60, true),

-- 🔥 INTIMITÉ & CONNEXION (61-75)
('L''intimité pour toi c''est :', 'intimité', '["🔗 Connexion", "🔥 Passion", "😊 Complicité", "💬 Expression"]', 61, true),
('Tu es plutôt :', 'intimité', '["🙈 Pudique", "💃 Expressif(ve)"]', 62, true),
('Ton rythme affectif :', 'intimité', '["🐢 Lent", "⚖️ Moyen", "🚀 Rapide"]', 63, true),
('Le plus important dans la connexion :', 'intimité', '["🤝 Confiance", "💕 Désir", "🛡️ Sécurité", "🦋 Liberté"]', 64, true),
('Tu préfères :', 'intimité', '["🌸 Douceur", "🔥 Intensité", "⚖️ Les deux"]', 65, true),
('Tu t''attaches :', 'intimité', '["⚡ Rapidement", "🐢 Lentement", "🦋 Rarement"]', 66, true),
('Tu es plutôt :', 'intimité', '["💝 Démonstratif(ve)", "🤫 Réservé(e)"]', 67, true),
('Pour toi, le couple doit garder :', 'intimité', '["🎭 Mystère", "📅 Routine", "🎁 Surprise", "⚓ Stabilité"]', 68, true),
('Le contact physique est :', 'intimité', '["💯 Essentiel", "👍 Important", "🤷 Optionnel"]', 69, true),
('La communication intime :', 'intimité', '["💎 Primordiale", "👍 Utile", "🤷 Facultative"]', 70, true),
('Tu préfères exprimer :', 'intimité', '["💬 Tes émotions", "🤲 Tes actions"]', 71, true),
('Tu es plutôt :', 'intimité', '["💚 Jaloux(se)", "🤝 Confiant(e)"]', 72, true),
('Ton niveau d''attachement :', 'intimité', '["💪 Fort", "⚖️ Modéré", "🦋 Faible"]', 73, true),
('Tu crois à la compatibilité intime ?', 'intimité', '["✅ Oui", "❌ Non", "🤔 Partiellement"]', 74, true),
('La passion doit être :', 'intimité', '["🔥 Permanente", "📈 Par phases", "⚓ Stable"]', 75, true),

-- 🌱 VALEURS & VISION (76-95)
('Valeur n°1 :', 'valeurs', '["🙏 Respect", "💎 Honnêteté", "🎯 Ambition", "🛡️ Loyauté"]', 76, true),
('Ton rêve principal :', 'valeurs', '["👨‍👩‍👧 Famille", "🏆 Réussite", "🦋 Liberté", "🌍 Impact"]', 77, true),
('Tu veux des enfants ?', 'valeurs', '["👶 Oui", "❌ Non", "🤔 Peut-être"]', 78, true),
('Le mariage pour toi :', 'valeurs', '["💍 Important", "🤷 Optionnel", "❌ Inutile"]', 79, true),
('Ton rapport à la spiritualité :', 'valeurs', '["🙏 Fort", "⚖️ Moyen", "🤷 Faible"]', 80, true),
('Tu préfères :', 'valeurs', '["👫 Construire à deux", "🚶 Évoluer chacun"]', 81, true),
('Le succès c''est :', 'valeurs', '["💰 Argent", "🦋 Liberté", "🏆 Accomplissement", "🌍 Influence"]', 82, true),
('Tu crois plus en :', 'valeurs', '["📋 Discipline", "✨ Inspiration"]', 83, true),
('Tu préfères :', 'valeurs', '["🛡️ Sécurité", "🎲 Prise de risque"]', 84, true),
('Ton modèle de couple :', 'valeurs', '["👨‍👩‍👧 Parents", "🎬 Films", "🌍 Réalité", "💭 Toi-même"]', 85, true),
('Ton plus grand objectif :', 'valeurs', '["💖 Amour", "🏆 Réussite", "🧘 Sérénité", "⚖️ Équilibre"]', 86, true),
('Le bonheur c''est :', 'valeurs', '["✨ Simplicité", "🦋 Liberté", "💖 Amour", "🏆 Succès"]', 87, true),
('Ta vision du couple :', 'valeurs', '["🤝 Équipe", "🤲 Partenaires", "💞 Fusion", "🦋 Indépendance"]', 88, true),
('Tu préfères :', 'valeurs', '["🐢 Construire lentement", "🔥 Vivre intensément"]', 89, true),
('Ta définition de la loyauté :', 'valeurs', '["💍 Fidélité", "🤲 Soutien", "🏠 Présence", "💎 Vérité"]', 90, true),
('Tu veux une relation :', 'valeurs', '["⚓ Stable", "📈 Évolutive", "🦋 Libre", "🔥 Passionnelle"]', 91, true),
('La priorité dans ta vie :', 'valeurs', '["👨‍👩‍👧 Famille", "💼 Travail", "💖 Amour", "🦋 Liberté"]', 92, true),
('Ton moteur :', 'valeurs', '["🔥 Passion", "🛡️ Sécurité", "🎯 Ambition", "🙏 Foi"]', 93, true),
('Le respect commence par :', 'valeurs', '["👂 L''écoute", "💎 La vérité", "🤲 Les actes", "🚧 Les limites"]', 94, true),
('Tu préfères :', 'valeurs', '["🤲 Donner", "🎁 Recevoir", "⚖️ Équilibrer"]', 95, true),

-- 🎯 COMPATIBILITÉ & MATCH (96-115)
('Tu crois aux tests de compatibilité ?', 'compatibilité', '["✅ Oui", "❌ Non", "🤔 Curieux(se)"]', 96, true),
('Tu préfères rencontrer :', 'compatibilité', '["🪞 Quelqu''un comme toi", "🔄 Ton opposé", "🎨 Un mélange"]', 97, true),
('Le feeling passe par :', 'compatibilité', '["👀 Le regard", "🗣️ La parole", "⚡ L''énergie", "😂 L''humour"]', 98, true),
('Tu te connectes plus :', 'compatibilité', '["🧠 Mentalement", "💖 Émotionnellement", "💪 Physiquement"]', 99, true),
('Tu préfères :', 'compatibilité', '["🏗️ Construire", "🔍 Découvrir", "🎵 Vibrer", "🛡️ Sécuriser"]', 100, true),
('L''important dans une rencontre :', 'compatibilité', '["🌿 Naturel", "🎁 Surprise", "🌊 Profondeur", "🎉 Fun"]', 101, true),
('Tu crois aux signes ?', 'compatibilité', '["✨ Oui", "❌ Non", "🤔 Parfois"]', 102, true),
('Tu préfères :', 'compatibilité', '["🐢 Lent mais sûr", "🚀 Rapide et intense"]', 103, true),
('Le plus important chez ton partenaire :', 'compatibilité', '["🧠 Mentalité", "💎 Valeurs", "✨ Physique", "🎯 Ambition"]', 104, true),
('Tu préfères :', 'compatibilité', '["⚓ La stabilité", "🎢 L''excitation"]', 105, true),
('Tu crois en la compatibilité des caractères ?', 'compatibilité', '["✅ Oui", "❌ Non", "🤔 Un peu"]', 106, true),
('La connexion idéale est :', 'compatibilité', '["🌊 Fluide", "🌀 Profonde", "🔥 Intense", "⚓ Stable"]', 107, true),
('Tu veux ressentir :', 'compatibilité', '["🛡️ Sécurité", "🔥 Passion", "🦋 Liberté", "🧘 Sérénité"]', 108, true),
('Le plus beau sentiment :', 'compatibilité', '["💖 Amour", "☮️ Paix", "🎢 Excitation", "🏆 Fierté"]', 109, true),
('Ton critère numéro 1 :', 'compatibilité', '["🙏 Respect", "💕 Attirance", "🔮 Vision", "💬 Communication"]', 110, true),
('Tu préfères :', 'compatibilité', '["📅 Prévisibilité", "🎁 Surprise"]', 111, true),
('Tu veux une relation :', 'compatibilité', '["✨ Simple", "🔥 Intense", "⚓ Stable", "📈 Évolutive"]', 112, true),
('Le couple idéal :', 'compatibilité', '["🤝 Équipe solide", "🔥 Duo passionné", "😊 Complices", "👯 Amis-amants"]', 113, true),
('Tu crois au hasard organisé ?', 'compatibilité', '["✨ Oui", "❌ Non", "🤔 Curieux(se)"]', 114, true),
('Ton couple rêvé :', 'compatibilité', '["☮️ Paisible", "🔥 Passionné", "🎯 Ambitieux", "🌍 Aventurier"]', 115, true);